
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-06T00:24:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "162a171714ec593ec45b96b9e9eebcaa1517bd0d",
 "version": "0+untagged.55.g162a171"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
