# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant/util/downloader'
require 'vagrant/ui'
require 'yaml'
require 'fileutils'
require 'digest'

## VM Creation & Provisioning
##############################################

Vagrant.configure(2) do |config|

  # Avoid random ssh key for demo purposes
  config.ssh.insert_key = false
  config.vbguest.auto_update = true
  # TODO template this file and get the bridge name
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  # TODO template this file and get the node
  config.vm.define "node" do |machine|
    # custom mount type
    # machine.vm.synced_folder '.', '/vagrant', type: user_config.vagrant_mount_method

    # allow explicit nil values in the machine_type to override the defaults
    machine.vm.box = 'mesosphere/dcos-centos-virtualbox'
    machine.vm.box_url = 'https://downloads.dcos.io/dcos-vagrant/metadata.json'
    machine.vm.box_version = '~> 0.9.2'

    machine.vm.provider 'virtualbox' do |v, override|
      v.cpus = 2
      v.memory = 2048

      # Manually configure DNS
      v.auto_nat_dns_proxy = false
      # NAT proxy is flakey (times out frequently)
      v.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
      # Host DNS resolution required to support host proxies and faster global DNS resolution
      v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      # Assign unique mac address
      v.customize ['modifyvm', :id, '--macaddress1', 'auto']

      # guest should sync time if more than 10s off host
      v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end
  end
end
