
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-05T16:51:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c887a360514c1d00cd7c4064858f80bc0b2d2687",
 "version": "0+untagged.46.gc887a36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
