
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-06T01:18:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "eed084208813c9bf0cf4ff753da85fe11909a7bb",
 "version": "0+untagged.61.geed0842"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
