
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-05-19T14:44:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8550cf77f0f8e9878ad4d6ec9980f675b656d966",
 "version": "0+untagged.71.g8550cf7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
